remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-slate
title: Chris Day's GitHub Pages
description: Chris Day's GitHub Pages
